on:
  push:
    branches:
      - testing # Automatically deploy on test branch
  workflow_dispatch: # Manually deploy on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies locally and compress
        run: |
          npm ci
          tar -czf node_modules.tar.gz node_modules

      - name: Deploy files including compressed node_modules
        uses: SamKirkland/FTP-Deploy-Action@v4.2.0
        with:
          server: ftp.theshippinghack.com
          username: ${{ secrets.TESTING_FTP_USERNAME }}
          password: ${{ secrets.TESTING_FTP_PASSWORD }}

      - name: Extract node_modules via FTP
        run: |
          curl -u ${{ secrets.TESTING_FTP_USERNAME }}:${{ secrets.TESTING_FTP_PASSWORD }} \
          ftp://ftp.theshippinghack.com/home/theshippinghack/testing.theshippinghack.com/ \
          --upload-file extract_node_modules.php
