name: CI/CD Workflow - Automatic for Test, Manual for Main

on:
  push:
    branches:
      - test # Automatically deploy on test branch
  workflow_dispatch: # Manually deploy on main branch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16.14.0

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

  security_scan:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:16.14.0

    steps:
      - uses: actions/checkout@v2

      - name: Security Scan
        uses: zricethezav/gitleaks-action@v1.5.0

      # Step 4: Create .env file dynamically
      - name: Create .env file dynamically
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Deploying to production server (main branch)..."
            echo "${{ secrets.ENV_FILE_CONTENT_PROD }}" > .env
          elif [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
            echo "Deploying to testing server (test branch)..."
            echo "${{ secrets.ENV_FILE_CONTENT_DEV }}" > .env
          else
            echo "Invalid branch. Exiting."
            exit 1
          fi

      # Step 5: Create config folder and files dynamically
      - name: Create config folder and files
        run: |
          echo "Creating config folder..."
          mkdir -p config
          echo "${{ secrets.CONFIG_JSON_CONTENT }}" > config/config.json

      # Step 6: Create .htaccess file dynamically
      - name: Create .htaccess file
        run: |
          echo "Creating .htaccess file..."
          echo "${{ secrets.HTACCESS_CONTENT }}" > .htaccess

      # Optional: Verify created files (Debugging only - Remove in production)
      - name: Verify files (Optional)
        run: |
          echo "Verifying created files..."
          ls -R
          cat .env
          cat config/config.json
          cat .htaccess

      # Step 7: Deploy files to the appropriate server
      - name: 📂 Sync files to server
        uses: SamKirkland/FTP-Deploy-Action@v4.2.0
        with:
          server: ftp.theshippinghack.com
          username: ${{ secrets.TESTING_FTP_USERNAME }}
          password: ${{ secrets.TESTING_FTP_PASSWORD }}
