name: CI/CD Workflow

on:
  push:
    branches:
      - testing # Automatically deploy on the test branch
  workflow_dispatch: # Manually deploy on the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16.14.0

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Archive node_modules
        run: tar -czf node_modules.tar.gz node_modules

      - name: Upload node_modules artifact
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules

      - name: Extract node_modules locally
        run: |
          echo "Extracting node_modules.tar.gz locally..."
          tar -xzf node_modules.tar.gz
          ls -l # List files for verification

      - name: Transfer all files including node_modules
        uses: SamKirkland/FTP-Deploy-Action@v4.2.0
        with:
          server: ftp.theshippinghack.com
          username: ${{ secrets.TESTING_FTP_USERNAME }}
          password: ${{ secrets.TESTING_FTP_PASSWORD }}
          local-dir: ./ # Ensure all files including node_modules are synchronized
          exclude: |
            .git*
            node_modules.tar.gz # Avoid uploading the tar file again

      - name: Verify deployment
        run: echo "Deployment completed successfully!"
